import { StatusCode } from "./types.ts"

export const t = () => {
  const now = new Date()
  return `${now.getFullYear()}/${(now.getMonth()+1).toString().padStart(2, "0")}/${now.getDate().toString().padStart(2, "0")} ${now.getHours().toString().padStart(2, "0")}:${now.getMinutes().toString().padStart(2, "0")}`
}

export const deriveStatusCodeFromNumber = (n: number): [StatusCode, string] => {
  switch (n) {
    case 100: return [StatusCode.CONTINUE, "CONTINUE"]
    case 101: return [StatusCode.SWITCHING_PROTOCOLS, "SWITCHING_PROTOCOLS"]
    case 102: return [StatusCode.PROCESSING, "PROCESSING"]
    case 103: return [StatusCode.EARLY_HINTS, "EARLY_HINTS"]
    case 200: return [StatusCode.SUCCESS, "SUCCESS"]
    case 201: return [StatusCode.CREATED, "CREATED"]
    case 202: return [StatusCode.ACCEPTED, "ACCEPTED"]
    case 203: return [StatusCode.NON_AUTHORITATIVE_INFORMATION, "NON_AUTHORITATIVE_INFORMATION"]
    case 204: return [StatusCode.NO_CONTENT, "NO_CONTENT"]
    case 205: return [StatusCode.RESET_CONTENT, "RESET_CONTENT"]
    case 206: return [StatusCode.PARTIAL_CONTENT, "PARTIAL_CONTENT"]
    case 207: return [StatusCode.MULTI_STATUS, "MULTI_STATUS"]
    case 208: return [StatusCode.ALREADY_REPORTED, "ALREADY_REPORTED"]
    case 226: return [StatusCode.IM_USED, "IM_USED"]
    case 300: return [StatusCode.MULTIPLE_CHOICES, "MULTIPLE_CHOICES"]
    case 301: return [StatusCode.MOVED_PERMANENTLY, "MOVED_PERMANENTLY"]
    case 302: return [StatusCode.FOUND, "FOUND"]
    case 303: return [StatusCode.SEE_OTHER, "SEE_OTHER"]
    case 304: return [StatusCode.NOT_MODIFIED, "NOT_MODIFIED"]
    case 305: return [StatusCode.USE_PROXY, "USE_PROXY"]
    case 307: return [StatusCode.TEMPORARY_REDIRECT, "TEMPORARY_REDIRECT"]
    case 308: return [StatusCode.PERMANENT_REDIRECT, "PERMANENT_REDIRECT"]
    case 400: return [StatusCode.BAD_REQUEST, "BAD_REQUEST"]
    case 401: return [StatusCode.UNAUTHORIZED, "UNAUTHORIZED"]
    case 402: return [StatusCode.PAYMENT_REQUIRED, "PAYMENT_REQUIRED"]
    case 403: return [StatusCode.FORBIDDEN, "FORBIDDEN"]
    case 404: return [StatusCode.NOT_FOUND, "NOT_FOUND"]
    case 405: return [StatusCode.METHOD_NOT_ALLOWED, "METHOD_NOT_ALLOWED"]
    case 406: return [StatusCode.NOT_ACCEPTABLE, "NOT_ACCEPTABLE"]
    case 407: return [StatusCode.PROXY_AUTHENTICATION_REQUIRED, "PROXY_AUTHENTICATION_REQUIRED"]
    case 408: return [StatusCode.REQUEST_TIMEOUT, "REQUEST_TIMEOUT"]
    case 409: return [StatusCode.CONFLICT, "CONFLICT"]
    case 410: return [StatusCode.GONE, "GONE"]
    case 411: return [StatusCode.LENGTH_REQUIRED, "LENGTH_REQUIRED"]
    case 412: return [StatusCode.PRECONDITION_FAILED, "PRECONDITION_FAILED"]
    case 413: return [StatusCode.CONTENT_TOO_LARGE, "CONTENT_TOO_LARGE"]
    case 414: return [StatusCode.URI_TOO_LONG, "URI_TOO_LONG"]
    case 415: return [StatusCode.UNSUPPORTED_MEDIA_TYPE, "UNSUPPORTED_MEDIA_TYPE"]
    case 416: return [StatusCode.RANGE_NOT_SATISFIABLE, "RANGE_NOT_SATISFIABLE"]
    case 417: return [StatusCode.EXPECTATION_FAILED, "EXPECTATION_FAILED"]
    case 418: return [StatusCode.IM_A_TEAPOT, "IM_A_TEAPOT"]
    case 421: return [StatusCode.MISDIRECTED_REQUEST, "MISDIRECTED_REQUEST"]
    case 422: return [StatusCode.UNPROCESSABLE_CONTENT, "UNPROCESSABLE_CONTENT"]
    case 423: return [StatusCode.LOCKED, "LOCKED"]
    case 424: return [StatusCode.FAILED_DEPENDENCY, "FAILED_DEPENDENCY"]
    case 425: return [StatusCode.TOO_EARLY, "TOO_EARLY"]
    case 426: return [StatusCode.UPGRADE_REQUIRED, "UPGRADE_REQUIRED"]
    case 428: return [StatusCode.PRECONDITION_REQUIRED, "PRECONDITION_REQUIRED"]
    case 429: return [StatusCode.TOO_MANY_REQUESTS, "TOO_MANY_REQUESTS"]
    case 431: return [StatusCode.REQUEST_HEADER_FIELDS_TOO_LARGE, "REQUEST_HEADER_FIELDS_TOO_LARGE"]
    case 451: return [StatusCode.UNAVAILABLE_FOR_LEGAL_REASONS, "UNAVAILABLE_FOR_LEGAL_REASONS"]
    case 500: return [StatusCode.INTERNAL_SERVER_ERROR, "INTERNAL_SERVER_ERROR"]
    case 501: return [StatusCode.NOT_IMPLEMENTED, "NOT_IMPLEMENTED"]
    case 502: return [StatusCode.BAD_GATEWAY, "BAD_GATEWAY"]
    case 503: return [StatusCode.SERVICE_UNAVAILABLE, "SERVICE_UNAVAILABLE"]
    case 504: return [StatusCode.GATEWAY_TIMEOUT, "GATEWAY_TIMEOUT"]
    case 505: return [StatusCode.HTTP_VERSION_NOT_SUPPORTED, "HTTP_VERSION_NOT_SUPPORTED"]
    case 506: return [StatusCode.VARIANT_ALSO_NEGOTIATES, "VARIANT_ALSO_NEGOTIATES"]
    case 507: return [StatusCode.INSUFFICIENT_STORAGE, "INSUFFICIENT_STORAGE"]
    case 508: return [StatusCode.LOOP_DETECTED, "LOOP_DETECTED"]
    case 510: return [StatusCode.NOT_EXTENDED, "NOT_EXTENDED"]
    case 511: return [StatusCode.NETWORK_AUTHENTICATION_REQUIRED, "NETWORK_AUTHENTICATION_REQUIRED"]
    default: return [StatusCode.INTERNAL_SERVER_ERROR, "INTERNAL_SERVER_ERROR"]
  }
}
